// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Address: typeof import('./src/components/vo/Address.vue')['default']
    Author: typeof import('./src/components/Author.vue')['default']
    AuthorGrid: typeof import('./src/components/ui/AuthorGrid.vue')['default']
    BaseDetailGrid: typeof import('./src/components/base-ui/BaseDetailGrid.vue')['default']
    BaseEntity: typeof import('./src/components/base-ui/BaseEntity.vue')['default']
    BaseGrid: typeof import('./src/components/base-ui/BaseGrid.vue')['default']
    BasePicker: typeof import('./src/components/base-ui/BasePicker.vue')['default']
    BaseSecurity: typeof import('./src/components/base-ui/BaseSecurity.vue')['default']
    Book: typeof import('./src/components/Book.vue')['default']
    BookGrid: typeof import('./src/components/ui/BookGrid.vue')['default']
    Boolean: typeof import('./src/components/primitives/Boolean.vue')['default']
    BuyNow: typeof import('./src/@core/components/BuyNow.vue')['default']
    BuyPlan: typeof import('./src/components/BuyPlan.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    Date: typeof import('./src/components/primitives/Date.vue')['default']
    Email: typeof import('./src/components/vo/Email.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    EventViewer: typeof import('./src/components/vo/EventViewer.vue')['default']
    File: typeof import('./src/components/vo/File.vue')['default']
    GetAllLibrary: typeof import('./src/components/GetAllLibrary.vue')['default']
    GetAllPoint: typeof import('./src/components/GetAllPoint.vue')['default']
    Index: typeof import('./src/components/pages/Index.vue')['default']
    LargeObject: typeof import('./src/components/primitives/LargeObject.vue')['default']
    Money: typeof import('./src/components/vo/Money.vue')['default']
    Number: typeof import('./src/components/primitives/Number.vue')['default']
    Payment: typeof import('./src/components/vo/Payment.vue')['default']
    Photo: typeof import('./src/components/vo/Photo.vue')['default']
    Point: typeof import('./src/components/Point.vue')['default']
    PointGrid: typeof import('./src/components/ui/PointGrid.vue')['default']
    Publishing: typeof import('./src/components/Publishing.vue')['default']
    PublishingGrid: typeof import('./src/components/ui/PublishingGrid.vue')['default']
    Rating: typeof import('./src/components/vo/Rating.vue')['default']
    ReadAllBooks: typeof import('./src/components/ReadAllBooks.vue')['default']
    Reading: typeof import('./src/components/Reading.vue')['default']
    ReadingGrid: typeof import('./src/components/ui/ReadingGrid.vue')['default']
    RequestPublish: typeof import('./src/components/RequestPublish.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveTemporaryScript: typeof import('./src/components/SaveTemporaryScript.vue')['default']
    Script: typeof import('./src/components/Script.vue')['default']
    ScriptGrid: typeof import('./src/components/ui/ScriptGrid.vue')['default']
    String: typeof import('./src/components/primitives/String.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    User: typeof import('./src/components/vo/User.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
    UserInfoGrid: typeof import('./src/components/ui/UserInfoGrid.vue')['default']
    Weather: typeof import('./src/components/vo/Weather.vue')['default']
  }
}
